name: Multi-Stage Pipeline

# Trigger options
on:
  workflow_dispatch:  # Enables manual trigger
    # inputs:
    #   run_build:
    #     description: 'Run Build Stage'
    #     required: true
    #     default: true
    #     type: boolean
    #   run_test:
    #     description: 'Run Test Stage'
    #     required: true
    #     default: true
    #     type: boolean
    #   run_deploy:
    #     description: 'Run Deploy Stage'
    #     required: true
    #     default: false
    #     type: boolean

jobs:
  # Stage 1: Build
  build:
    runs-on: ubuntu-latest
    #if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/

  # Stage 2: Test (depends on build)
  test:
    runs-on: ubuntu-latest
    needs: build
    #if: ${{ always() && (needs.build.result == 'success' || needs.build.result == 'skipped') && (github.event_name != 'workflow_dispatch' || inputs.run_test) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run unit tests
        run: npm test
      
      - name: Run integration tests
        run: npm run test:integration

  # Stage 3: Deploy (depends on test)
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    #if: ${{ always() && (needs.test.result == 'success' || needs.test.result == 'skipped') && (github.event_name != 'workflow_dispatch' || inputs.run_deploy) }}
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/
      
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Your deployment commands here